package br.com.listme.data.model

data class List(
    var id: String?, // Document ID (will be generated by Firestore)
    val name: String,
    val createdAt: String
) {
    constructor() : this(
        id = null,
        name = "",
        createdAt = ""
    )
    constructor(name: String, createdAt: String) : this(id = null, name = name, createdAt = createdAt)
}